### ISSUE TITLE
FastSAM module doesn't handle non-detected targets well

### ISSUE THREAD

**Issue by petercham** [ultralytics/assets#85]
!!! Exception during processing !!! 'NoneType' object has no attribute 'data'
Traceback (most recent call last):
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Work\SD-ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\face_nodes.py", line 340, in swap_faces
    face_masks, _, _, _, _ = segmentor.predict(cropped_img, segment_model, conf=0.9, iou=0.8, valid=False, text=None, box=None, point=crop_center, sort_method="original")
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\segment_nodes.py", line 179, in predict
    return super().predict(image, fast_sam_model, conf, iou, valid, add_params, sort_method, debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\segment_nodes.py", line 54, in predict
    results = model.get(image, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\predictor.py", line 161, in _predict_process
    result = self.get_result(img, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\predictor.py", line 334, in get_result
    results, max_conf, best_size = self.segm_size_prob(source, orig_left, orig_right, target_conf, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\predictor.py", line 555, in segm_size_prob
    results = self._predict(source, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Hjh_nodes\predict\ultralytics_fastsam.py", line 55, in _predict
    return self.model(source, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\fastsam\model.py", line 50, in predict
    return super().predict(source, stream, prompts=prompts, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\predictor.py", line 169, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\predictor.py", line 262, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\fastsam\predict.py", line 44, in postprocess
    return self.prompt(results, bboxes=bboxes, points=points, labels=labels, texts=texts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\fastsam\predict.py", line 67, in prompt
    masks = result.masks.data
            ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

This error does not occur if the target is detected, but if it is not detected in the predicted image it will still try to extract tasks.data in fastsam/predict.py.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @petercham, thank you for submitting a 🚀 issue related to the `ultralytics/assets` repository. To help us address your concern as quickly and efficiently as possible, could you please provide the following information?

1. A clear and concise description of the bug you're experiencing.
2. A minimum reproducible example (MRE) that demonstrates the issue. You can find guidance on creating an MRE [here](https://docs.ultralytics.com/help/minimum_reproducible_example/).
3. Details about your environment, including:
   - Operating System
   - Python version
   - Package versions (e.g., ultralytics version, PyTorch version)
4. The behavior you expected versus what actually occurred.
5. Any specific error messages or logs you have encountered, specifically focusing on how the `NoneType` object situation arises.

Please ensure you've searched existing issues to prevent duplicates. If you have additional information or updates, kindly comment on this issue. 

Note that this is an automated response 🤖, but rest assured, an Ultralytics engineer will review your issue and assist you soon. Thank you for helping us improve our project! 😊

**Comment by pderrenger** [comment]
@petercham thank you for bringing this issue to our attention. The error you're encountering seems to be related to handling cases where no objects are detected. To address this, ensure you're using the latest version of the FastSAM module, as updates may contain important bug fixes. Additionally, you may need to add a check in your code to handle cases where no detection results are returned, preventing attempts to access non-existent attributes. If the problem persists, consider opening an issue on the FastSAM GitHub repository with detailed information for further assistance.
